const FD_CREST = (id) => `https://crests.football-data.org/${id}.png`;
const FD_LEAGUE = (code) => `https://crests.football-data.org/${code}.png`;

/** Códigos con escudo de liga válido en crests.football-data.org */
const VALID_FD_LEAGUE_CODES = new Set([
  'PL',
  'PD',
  'SA',
  'BL1',
  'BL2',
  'FL1',
  'FL2',
  'PPL',
  'ED',
  'ELC',
  'SPL',
  'MLS',
  'SB',
  'CLI',
  'EL',
  'UCL',
  'CL',
]);

/** Escudo de liga vía Wikimedia (Special:FilePath resuelve el thumbnail). */
const WM_EMBLEM = (file) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=120`;

function leagueEmblemUrl(bucket) {
  if (bucket.emblemFile) return WM_EMBLEM(bucket.emblemFile);
  if (VALID_FD_LEAGUE_CODES.has(bucket.code)) return FD_LEAGUE(bucket.code);
  return null;
}

/** Liga → país + escudo de competición + clubes (nombre → id FD opcional). */
const LEAGUE_BUCKETS = [
  {
    code: 'PL',
    leagueName: 'Premier League',
    country: 'Inglaterra',
    clubs: {
      Arsenal: 57,
      'Aston Villa': 58,
      'AFC Bournemouth': 1044,
      Bournemouth: 1044,
      Brentford: 402,
      'Brighton & Hove Albion': 397,
      Burnley: 328,
      Chelsea: 61,
      'Crystal Palace': 354,
      Everton: 62,
      Fulham: 63,
      Liverpool: 64,
      'Luton Town': 389,
      'Manchester City': 65,
      'Manchester United': 66,
      'Newcastle United': 67,
      'Norwich City': 68,
      'Nottingham Forest': 351,
      'Sheffield United': 356,
      'Tottenham Hotspur': 73,
      'West Ham United': 563,
      'Wolverhampton Wanderers': 76,
      'Leicester City': 338,
      Southampton: 340,
      'Ipswich Town': 113,
      Watford: 346,
      'West Bromwich Albion': 74,
      'Coventry City': 1076,
      'Birmingham City': 332,
      'Middlesbrough': 343,
      'Hull City': 322,
      'Stoke City': 70,
      'Huddersfield Town': 384,
      'Plymouth Argyle': 1075,
      'Mansfield Town': null,
      'Crawley Town': null,
      'Milton Keynes Dons': null,
    },
  },
  {
    code: 'PD',
    leagueName: 'La Liga',
    country: 'España',
    clubs: {
      Barcelona: 81,
      'Real Madrid': 86,
      'Atletico Madrid': 78,
      Sevilla: 559,
      Valencia: null,
      Villarreal: 94,
      'Real Sociedad': 92,
      'Athletic Club': 77,
      'Real Betis': 90,
      Getafe: 82,
      Mallorca: 89,
      Osasuna: 79,
      Girona: 298,
      Almeria: 400,
      'Las Palmas': 275,
      'Rayo Vallecano': 87,
      'Celta Vigo': 558,
      'Real Valladolid': 250,
      'Real Zaragoza': null,
      Albacete: null,
    },
  },
  {
    code: 'SA',
    leagueName: 'Serie A',
    country: 'Italia',
    clubs: {
      'Inter Milan': 108,
      'AC Milan': 98,
      Juventus: 109,
      Napoli: 113,
      Roma: 100,
      Lazio: null,
      Atalanta: 102,
      Fiorentina: 99,
      Torino: 586,
      Bologna: 103,
      Udinese: 115,
      Genoa: 107,
      Cagliari: 104,
      Empoli: 445,
      Lecce: 589,
      Salernitana: 471,
      Como: null,
      Cremonese: null,
      Parma: null,
      'Juventus Next Gen': null,
    },
  },
  {
    code: 'BL1',
    leagueName: 'Bundesliga',
    country: 'Alemania',
    clubs: {
      'Bayern Munich': 5,
      'Borussia Dortmund': 4,
      'RB Leipzig': 721,
      'Bayer Leverkusen': 3,
      'Eintracht Frankfurt': 19,
      Wolfsburg: 11,
      'Borussia Monchengladbach': 18,
      Freiburg: 17,
      Stuttgart: 10,
      Hoffenheim: 2,
      Augsburg: 16,
      Mainz: 15,
      'Union Berlin': 28,
      'Werder Bremen': 12,
      Bochum: null,
      'Holstein Kiel': null,
      'Hamburg': 7,
      'St. Pauli': null,
      'FC Cologne': 1,
      '1. FC Köln': 1,
      '1. FC Koln': 1,
    },
  },
  {
    code: 'BL2',
    leagueName: '2. Bundesliga',
    country: 'Alemania',
    clubs: {
      'Arminia Bielefeld': 44,
      'Eintracht Braunschweig': 39,
      'Hansa Rostock': 30,
      'Hertha BSC': 9,
      'Karlsruher SC': 6,
      '1. FC Kaiserslautern': 25,
      'Fortuna Düsseldorf': 8,
      'Fortuna Dusseldorf': 8,
      'Hannover 96': 13,
      '1. FC Nürnberg': 14,
      '1. FC Nurnberg': 14,
      'SC Paderborn': 29,
      'SV Elversberg': null,
      'SV Darmstadt 98': 24,
    },
  },
  {
    code: 'FL1',
    leagueName: 'Ligue 1',
    country: 'Francia',
    clubs: {
      'Paris Saint-Germain': 524,
      Monaco: 548,
      Lyon: 523,
      Marseille: 516,
      Lille: 521,
      Nice: 522,
      Lens: 546,
      Rennes: 529,
      Strasbourg: 576,
      Nantes: 543,
      Montpellier: 518,
      Reims: 547,
      Brest: 512,
      Metz: 545,
      Auxerre: null,
      Angers: null,
      Toulouse: 511,
      Clermont: 541,
      'Saint-Etienne': 527,
      Amiens: null,
      Grenoble: null,
      Bastia: null,
      Caen: null,
      Dunkerque: null,
      Lorient: 525,
      Rodez: null,
      'Paris FC': null,
      'Paris 13 Atletico': null,
      Versailles: null,
    },
  },
  {
    code: 'ED',
    leagueName: 'Eredivisie',
    country: 'Países Bajos',
    clubs: {
      Ajax: 678,
      PSV: 674,
      Feyenoord: 675,
      AZ: 682,
      'AZ Alkmaar': 682,
      Twente: 673,
      'FC Twente': 673,
      Utrecht: 676,
      Heerenveen: 671,
      Groningen: null,
      Excelsior: null,
      'NAC Breda': null,
      'RKC Waalwijk': null,
      Vitesse: null,
      'Almere City': null,
      'De Graafschap': null,
      'TOP Oss': null,
    },
  },
  {
    code: 'PPL',
    leagueName: 'Primeira Liga',
    country: 'Portugal',
    clubs: {
      Porto: 503,
      Benfica: 1903,
      'Sporting CP': 498,
      Braga: null,
      Boavista: null,
      'Casa Pia': null,
      Estoril: null,
      Moreirense: null,
      Vizela: null,
      'Vitoria Guimaraes': null,
      Feirense: null,
      Tondela: null,
    },
  },
  {
    code: 'A1',
    leagueName: 'Bundesliga (Austria)',
    country: 'Austria',
    clubs: {
      'Red Bull Salzburg': 201,
      Salzburg: 201,
      'Rapid Vienna': 202,
      'Austria Vienna': null,
      LASK: null,
      Sturm: null,
    },
  },
  {
    code: 'SL1',
    emblemFile: 'RZ_BSL_Logo_Portrait_RGB.svg',
    leagueName: 'Super League',
    country: 'Suiza',
    clubs: {
      Basel: 551,
      'Young Boys': 548,
      'Grasshopper': 547,
      Servette: null,
      Lugano: null,
      Sion: null,
      'St. Gallen': null,
    },
  },
  {
    code: 'B1',
    leagueName: 'Jupiler Pro League',
    country: 'Bélgica',
    clubs: {
      Anderlecht: 1104,
      'Club Brugge': 1103,
      'Cercle Brugge': null,
      Genk: 1102,
      Gent: null,
      'Union Saint-Gilloise': null,
      'Standard Liege': null,
      'Sint-Truiden': null,
      Westerlo: null,
      Eupen: null,
    },
  },
  {
    code: 'SC1',
    leagueName: 'Scottish Premiership',
    country: 'Escocia',
    clubs: {
      Celtic: 732,
      Rangers: 730,
      'Heart of Midlothian': null,
      Hibernian: null,
      'St. Mirren': null,
    },
  },
  {
    code: 'ELC',
    leagueName: 'Championship',
    country: 'Inglaterra',
    clubs: {
      'Leeds United': 341,
      'Leicester City': 338,
      Southampton: 340,
      'Sheffield United': 356,
      'West Bromwich Albion': 74,
      'Cardiff City': 715,
      Portsmouth: 325,
      'Norwich City': 68,
      'Ipswich Town': 113,
      Watford: 346,
      'Coventry City': 1076,
      'Middlesbrough': 343,
      'Stoke City': 70,
    },
  },
  {
    code: 'MLS',
    leagueName: 'MLS',
    country: 'Estados Unidos',
    clubs: {
      'Inter Miami': null,
      LAFC: null,
      'LA Galaxy': null,
      'Atlanta United': null,
      'Austin FC': null,
      'Charlotte FC': null,
      'Chicago Fire': null,
      'Columbus Crew': null,
      'FC Dallas': null,
      'Houston Dynamo': null,
      'Minnesota United': null,
      'Nashville SC': null,
      'New England Revolution': null,
      'New York Red Bulls': null,
      'Orlando City': null,
      'Philadelphia Union': null,
      'Portland Timbers': null,
      'Real Salt Lake': null,
      'San Jose Earthquakes': null,
      'Seattle Sounders': null,
      'Sporting Kansas City': null,
      'Toronto FC': null,
      'Vancouver Whitecaps': null,
      'San Diego FC': null,
    },
  },
  {
    code: 'SPL',
    leagueName: 'Saudi Pro League',
    country: 'Arabia Saudita',
    clubs: {
      'Al Hilal': null,
      'Al Nassr': null,
      'Al Ittihad': null,
      'Al Ahli': null,
      'Al Ettifaq': null,
      'Al Qadsiah': null,
      'Al Qadsia': null,
      'Al Fayha': null,
      'Al Khaleej': null,
      'Al Riyadh': null,
      'Al Hazem': null,
      'Al Wehda': null,
      'Al Ula': null,
      Damac: null,
      Abha: null,
      'Al Faisaly': null,
      'Al Shabab': null,
    },
  },
  {
    code: 'SB',
    leagueName: 'Brasileirão',
    country: 'Brasil',
    clubs: {
      Flamengo: null,
      Fluminense: null,
      Palmeiras: null,
      Corinthians: null,
      'Atletico Mineiro': null,
      Internacional: null,
      Gremio: null,
      Botafogo: null,
      'Athletico Paranaense': null,
      Bahia: null,
      Cuiaba: null,
      Vasco: null,
      'Vasco da Gama': null,
      'Sao Paulo': null,
      Santos: null,
      'Red Bull Bragantino': null,
      Fortaleza: null,
      Cruzeiro: null,
      'America Mineiro': null,
    },
  },
  {
    code: 'ARG',
    leagueName: 'Liga Profesional',
    country: 'Argentina',
    clubs: {
      'River Plate': null,
      'Racing Club': null,
      'Boca Juniors': null,
      Independiente: null,
      Lanus: null,
      Huracan: null,
      Talleres: null,
      'San Lorenzo': null,
    },
  },
  {
    code: 'LMX',
    leagueName: 'Liga MX',
    country: 'México',
    clubs: {
      'Club America': null,
      Guadalajara: null,
      'Cruz Azul': null,
      Monterrey: null,
      Toluca: null,
      'Pumas UNAM': null,
      Atlas: null,
      Leon: null,
      Tigres: null,
      Pachuca: null,
    },
  },
  {
    code: 'TSL',
    emblemFile: 'Süper_Lig_logo.svg',
    leagueName: 'Süper Lig',
    country: 'Turquía',
    clubs: {
      Galatasaray: null,
      Fenerbahce: null,
      Besiktas: null,
      Trabzonspor: null,
      Basaksehir: null,
      Antalyaspor: null,
      Kasimpasa: null,
      Kayserispor: null,
      Sivasspor: null,
      Rizespor: null,
      Ankaragucu: null,
      Gaziantep: null,
      Karagumruk: null,
      Pendikspor: null,
      Adana: null,
      'Adana Demirspor': null,
    },
  },
  {
    code: 'GSL',
    leagueName: 'Super League Greece',
    country: 'Grecia',
    clubs: {
      Olympiacos: null,
      Panathinaikos: null,
      AEK: null,
      'AEK Athens': null,
      PAOK: null,
      Aris: null,
    },
  },
  {
    code: 'HNL',
    leagueName: 'HNL',
    country: 'Croacia',
    clubs: {
      'Dinamo Zagreb': null,
      Rijeka: null,
      'Hajduk Split': null,
    },
  },
  {
    code: 'SSL',
    leagueName: 'SuperLiga',
    country: 'Serbia',
    clubs: {
      'Crvena zvezda': null,
      'Red Star Belgrade': null,
      Partizan: null,
      'FK TSC': null,
    },
  },
  {
    code: 'CZE',
    leagueName: 'Fortuna Liga',
    country: 'Rep. Checa',
    clubs: {
      'Sparta Prague': null,
      'Slavia Prague': null,
      'Viktoria Plzen': null,
      Slovacko: null,
    },
  },
  {
    code: 'DEN',
    leagueName: 'Superliga',
    country: 'Dinamarca',
    clubs: {
      Copenhagen: null,
      Midtjylland: null,
      Brondby: null,
      Nordsjaelland: null,
      Silkeborg: null,
      OB: null,
    },
  },
  {
    code: 'NOR',
    leagueName: 'Eliteserien',
    country: 'Noruega',
    clubs: {
      'Bodo/Glimt': null,
      Molde: null,
      Rosenborg: null,
      Lillestrom: null,
      'Lillestrøm': null,
      Viking: null,
    },
  },
  {
    code: 'SWE',
    leagueName: 'Allsvenskan',
    country: 'Suecia',
    clubs: {
      AIK: null,
      Hammarby: null,
      Malmo: null,
      Brommapojkarna: null,
    },
  },
  {
    code: 'J1',
    leagueName: 'J1 League',
    country: 'Japón',
    clubs: {
      'Sanfrecce Hiroshima': null,
      'Machida Zelvia': null,
      'Shonan Bellmare': null,
    },
  },
  {
    code: 'K1',
    leagueName: 'K League',
    country: 'Corea del Sur',
    clubs: {
      'Jeonbuk Hyundai': null,
      'Ulsan HD': null,
      'Daegu FC': null,
      'Suwon Samsung Bluewings': null,
    },
  },
  {
    code: 'AUS',
    leagueName: 'A-League',
    country: 'Australia',
    clubs: {
      'Melbourne City': null,
      'Perth Glory': null,
      'Macarthur FC': null,
      'Wellington Phoenix': null,
      'Western Sydney Wanderers': null,
      'Newcastle Jets': null,
    },
  },
  {
    code: 'RSA',
    leagueName: 'Premier Soccer League',
    country: 'Sudáfrica',
    clubs: {
      'Mamelodi Sundowns': null,
      'Orlando Pirates': null,
      'Kaizer Chiefs': null,
      AmaZulu: null,
      'Stellenbosch': null,
      'Polokwane City': null,
      'Sekhukhune United': null,
      'Richards Bay': null,
    },
  },
  {
    code: 'EGY',
    leagueName: 'Premier League',
    country: 'Egipto',
    clubs: {
      'Al Ahly': null,
      Zamalek: null,
      Pyramids: null,
    },
  },
  {
    code: 'MAR',
    leagueName: 'Botola Pro',
    country: 'Marruecos',
    clubs: {
      Wydad: null,
      'FAR Rabat': null,
      'RS Berkane': null,
    },
  },
  {
    code: 'QAT',
    leagueName: 'Stars League',
    country: 'Catar',
    clubs: {
      'Al Sadd': null,
      'Al Duhail': null,
      'Al Arabi': null,
      'Al Gharafa': null,
      'Al Wakrah': null,
      'Al Sailiya': null,
      'Qatar SC': null,
      'Al Ahli Doha': null,
      Muaither: null,
      'Al Shamal': null,
    },
  },
  {
    code: 'UAE',
    leagueName: 'Pro League',
    country: 'Emiratos Árabes',
    clubs: {
      'Al Ain': null,
      'Al Jazira': null,
      'Al Wahda': null,
      Shabab: null,
      'Shabab Al Ahli': null,
      Kalba: null,
    },
  },
  {
    code: 'COL',
    leagueName: 'Liga BetPlay',
    country: 'Colombia',
    clubs: {
      'Atletico Nacional': null,
      Millonarios: null,
      Junior: null,
    },
  },
  {
    code: 'ECU',
    leagueName: 'Liga Pro',
    country: 'Ecuador',
    clubs: {
      'LDU Quito': null,
      'Independiente del Valle': null,
    },
  },
  {
    code: 'CHI',
    leagueName: 'Primera División',
    country: 'Chile',
    clubs: {
      Cobresal: null,
      'Coquimbo Unido': null,
      'Universidad Catolica': null,
    },
  },
  {
    code: 'PER',
    leagueName: 'Liga 1',
    country: 'Perú',
    clubs: {
      'Cusco FC': null,
      Universitario: null,
    },
  },
  {
    code: 'CRC',
    leagueName: 'Primera División',
    country: 'Costa Rica',
    clubs: {
      'Deportivo Saprissa': null,
      'Herediano': null,
    },
  },
  {
    code: 'HON',
    leagueName: 'Liga Nacional',
    country: 'Honduras',
    clubs: {
      Olimpia: null,
      'Marathón': null,
      'Marathon': null,
      Motagua: null,
    },
  },
  {
    code: 'PAN',
    leagueName: 'Liga Panameña',
    country: 'Panamá',
    clubs: {
      'Plaza Amador': null,
      Municipal: null,
      Nacional: null,
    },
  },
  {
    code: 'UZB',
    leagueName: 'Super League',
    country: 'Uzbekistán',
    clubs: {
      Pakhtakor: null,
      Nasaf: null,
      Navbahor: null,
      Bunyodkor: null,
      AGMK: null,
    },
  },
  {
    code: 'KAZ',
    leagueName: 'Premier League',
    country: 'Kazajistán',
    clubs: {
      Ordabasy: null,
      Tobol: null,
    },
  },
  {
    code: 'IRN',
    leagueName: 'Persian Gulf Pro League',
    country: 'Irán',
    clubs: {
      Persepolis: null,
      Esteghlal: null,
      Sepahan: null,
      'Mes Rafsanjan': null,
    },
  },
  {
    code: 'IRQ',
    leagueName: 'Stars League',
    country: 'Irak',
    clubs: {
      'Al Shorta': null,
      'Al Zawraa': null,
    },
  },
  {
    code: 'JOR',
    leagueName: 'Pro League',
    country: 'Jordania',
    clubs: {
      'Al Hussein': null,
      'Al Wehdat': null,
      'Al Salt': null,
    },
  },
  {
    code: 'IND',
    leagueName: 'ISL',
    country: 'India',
    clubs: {
      Bengaluru: null,
    },
  },
  {
    code: 'CHN',
    leagueName: 'Super League',
    country: 'China',
    clubs: {
      'Changchun Yatai': null,
    },
  },
  {
    code: 'RPL',
    leagueName: 'Premier League',
    country: 'Rusia',
    clubs: {
      'CSKA Moscow': null,
      'Dinamo Moscow': null,
      'Dynamo Moscow': null,
      Krasnodar: null,
      Rostov: null,
      'Rubin Kazan': null,
      'Spartak Moscow': null,
    },
  },
  {
    code: 'UKR',
    leagueName: 'Premier League',
    country: 'Ucrania',
    clubs: {
      'Shakhtar Donetsk': null,
    },
  },
  {
    code: 'POL',
    leagueName: 'Ekstraklasa',
    country: 'Polonia',
    clubs: {
      Cracovia: null,
      'Lech Poznan': null,
      'Lech Poznań': null,
      'Rakow Czestochowa': null,
      'Raków Częstochowa': null,
    },
  },
  {
    code: 'HUN',
    leagueName: 'NB I',
    country: 'Hungría',
    clubs: {
      Ferencvaros: null,
      'Ferencváros': null,
    },
  },
  {
    code: 'BUL',
    leagueName: 'First League',
    country: 'Bulgaria',
    clubs: {
      Ludogorets: null,
    },
  },
  {
    code: 'ISR',
    leagueName: 'Premier League',
    country: 'Israel',
    clubs: {
      'Maccabi Haifa': null,
      'Maccabi Tel Aviv': null,
    },
  },
  {
    code: 'CYP',
    leagueName: 'First Division',
    country: 'Chipre',
    clubs: {
      'Aris Limassol': null,
      'Olympiakos Nicosia': null,
      Pafos: null,
    },
  },
  {
    code: 'ARM',
    leagueName: 'Premier League',
    country: 'Armenia',
    clubs: {
      'Ararat-Armenia': null,
    },
  },
  {
    code: 'SVK',
    leagueName: 'Fortuna Liga',
    country: 'Eslovaquia',
    clubs: {
      'AS Trencin': null,
      'AS Trenčín': null,
      Kosice: null,
      'Košice': null,
    },
  },
  {
    code: 'TUN',
    leagueName: 'Ligue 1',
    country: 'Túnez',
    clubs: {
      'Club Africain': null,
      Esperance: null,
      'Espérance': null,
    },
  },
  {
    code: 'KWT',
    leagueName: 'Premier League',
    country: 'Kuwait',
    clubs: {
      'Kuwait SC': null,
    },
  },
  {
    code: 'AZE',
    leagueName: 'Premier League',
    country: 'Azerbaiyán',
    clubs: {
      Qarabag: null,
      Qarabağ: null,
    },
  },
  {
    code: 'IRL',
    leagueName: 'League of Ireland',
    country: 'Irlanda',
    clubs: {
      'Shamrock Rovers': null,
      'Sligo Rovers': null,
    },
  },
  {
    code: 'MYS',
    leagueName: 'Super League',
    country: 'Malasia',
    clubs: {
      Selangor: null,
    },
  },
  {
    code: 'THA',
    leagueName: 'Thai League 1',
    country: 'Tailandia',
    clubs: {
      'Port FC': null,
    },
  },
  {
    code: 'SUR',
    leagueName: 'Hoofdklasse',
    country: 'Surinam',
    clubs: {
      'SV Robinhood': null,
    },
  },
  {
    code: 'CIV',
    leagueName: 'Ligue 1',
    country: 'Costa de Marfil',
    clubs: {
      'San Pedro': null,
    },
  },
];

const CLUB_ALIASES = {
  'fc cologne': 'FC Cologne',
  '1. fc cologne': 'FC Cologne',
  '1 fc koln': 'FC Cologne',
  'bodo/glimt': 'Bodo/Glimt',
  'crvena zvezda': 'Red Star Belgrade',
  'red star belgrade': 'Red Star Belgrade',
  'dynamo moscow': 'Dinamo Moscow',
  'dinamo moscow': 'Dinamo Moscow',
};

const COUNTRY_NAMES = new Set(
  [
    'Austria',
    'Bosnia-Herzegovina',
    'Bosnia and Herzegovina',
    'Germany',
    'France',
    'Spain',
    'Italy',
    'England',
    'Portugal',
    'Netherlands',
    'Belgium',
    'Switzerland',
    'Croatia',
    'Serbia',
    'Poland',
    'Turkey',
    'Greece',
    'Ukraine',
    'Russia',
    'Brazil',
    'Argentina',
    'Mexico',
    'USA',
    'Japan',
    'South Korea',
    'Morocco',
    'Egypt',
    'Senegal',
    'Nigeria',
    'Cameroon',
    'Ghana',
    'Tunisia',
    'Algeria',
    'Iran',
    'Qatar',
    'Saudi Arabia',
    'Uruguay',
    'Colombia',
    'Chile',
    'Ecuador',
    'Peru',
    'Paraguay',
    'Venezuela',
    'Canada',
    'Costa Rica',
    'Honduras',
    'Panama',
    'Jamaica',
    'Scotland',
    'Wales',
    'Northern Ireland',
    'Ireland',
    'Czech Republic',
    'Slovakia',
    'Hungary',
    'Romania',
    'Bulgaria',
    'Denmark',
    'Sweden',
    'Norway',
    'Finland',
    'Iceland',
    'China',
    'Australia',
    'New Zealand',
    'India',
    'Iraq',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Syria',
    'Uzbekistan',
    'Kazakhstan',
    'Georgia',
    'Armenia',
    'Azerbaijan',
    'Israel',
    'South Africa',
    'Kenya',
    'Angola',
    'Zambia',
    'Zimbabwe',
  ].map((c) => c.toLowerCase())
);

const clubIndex = new Map();

function normalizeClubKey(name) {
  return String(name || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function buildIndex() {
  if (clubIndex.size) return;
  for (const bucket of LEAGUE_BUCKETS) {
    for (const [clubName, teamId] of Object.entries(bucket.clubs)) {
      const key = normalizeClubKey(clubName);
      clubIndex.set(key, {
        clubName,
        country: bucket.country,
        leagueName: bucket.leagueName,
        leagueCode: bucket.code,
        leagueEmblemUrl: leagueEmblemUrl(bucket),
        clubCrestUrl: teamId ? FD_CREST(teamId) : null,
        footballDataClubId: teamId ?? null,
      });
    }
  }
}

export function isLikelyCountryLabel(value) {
  if (!value) return false;
  return COUNTRY_NAMES.has(String(value).toLowerCase().trim());
}

function formatClubMeta(entry = {}) {
  return {
    clubCountry: entry.clubCountry || entry.country || '',
    clubCrestUrl: entry.clubCrestUrl ?? null,
    leagueName: entry.leagueName || '',
    leagueEmblemUrl: entry.leagueEmblemUrl ?? null,
    footballDataClubId: entry.footballDataClubId ?? null,
  };
}

export function resolveClubMeta(clubName, stored = {}) {
  if (!clubName || isLikelyCountryLabel(clubName)) {
    return formatClubMeta(stored);
  }

  buildIndex();
  const key = normalizeClubKey(CLUB_ALIASES[normalizeClubKey(clubName)] || clubName);
  const hit = clubIndex.get(key);
  const resolved = hit ? formatClubMeta(hit) : formatClubMeta();

  return {
    clubCountry: stored.clubCountry || resolved.clubCountry,
    clubCrestUrl: stored.clubCrestUrl || resolved.clubCrestUrl,
    leagueName: stored.leagueName || resolved.leagueName,
    leagueEmblemUrl: stored.leagueEmblemUrl || resolved.leagueEmblemUrl,
    footballDataClubId: stored.footballDataClubId ?? resolved.footballDataClubId,
  };
}

export function enrichClubFields(player) {
  const clubName = player.currentClub || '';
  const fromStored = {
    clubCountry: player.clubCountry,
    clubCrestUrl: player.clubCrestUrl,
    leagueName: player.leagueName,
    leagueEmblemUrl: player.leagueEmblemUrl,
    footballDataClubId: player.footballDataClubId,
  };
  const meta = resolveClubMeta(clubName, fromStored);
  return {
    currentClub: isLikelyCountryLabel(clubName) ? '' : clubName,
    clubCountry: meta.clubCountry,
    clubCrestUrl: meta.clubCrestUrl,
    leagueName: meta.leagueName,
    leagueEmblemUrl: meta.leagueEmblemUrl,
    footballDataClubId: meta.footballDataClubId,
  };
}
