import dotenv from 'dotenv';

dotenv.config();

export const env = {
  port: Number(process.env.PORT || 5000),
  mongodbUri: process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/mundial2026',
  jwtSecret: process.env.JWT_SECRET || 'dev-secret-change-me',
  clientOrigin: process.env.CLIENT_ORIGIN || 'http://localhost:5173',
  worldCupApiUrl: process.env.WORLD_CUP_API_URL || 'https://worldcup26.ir',
  worldCupSyncEmail: process.env.WORLD_CUP_SYNC_EMAIL || '',
  worldCupSyncPassword: process.env.WORLD_CUP_SYNC_PASSWORD || '',
  syncIntervalMs: Number(process.env.SYNC_INTERVAL_MS || 60000),
  syncIntervalLiveMs: Number(process.env.SYNC_INTERVAL_LIVE_MS || 15000),
  kickoffWatchIntervalMs: Number(process.env.KICKOFF_WATCH_MS || 15000),
  simulationEnabled: process.env.SIMULATION_ENABLED !== 'false',
  adminUsername: process.env.ADMIN_USERNAME || '',
  adminPassword: process.env.ADMIN_PASSWORD || '',
  adminJwtExpires: process.env.ADMIN_JWT_EXPIRES || '8h',
  footballDataApiToken: process.env.FOOTBALL_DATA_API_TOKEN || '',
  footballDataApiUrl: process.env.FOOTBALL_DATA_API_URL || 'https://api.football-data.org/v4',
  fifaApiUrl: process.env.FIFA_API_URL || 'https://api.fifa.com/api/v3',
  fifaCompetitionId: process.env.FIFA_COMPETITION_ID || '17',
  fifaSeasonId: process.env.FIFA_SEASON_ID || '285023',
  fifaReportAssetPrefix: process.env.FIFA_REPORT_ASSET_PREFIX || 'ce281',
  fifaReportIdBase: Number(process.env.FIFA_REPORT_ID_BASE || 12451),
  aiPredictionsEnabled: process.env.AI_PREDICTIONS_ENABLED !== 'false',
  aiUserEmail: (process.env.AI_USER_EMAIL || 'predictivemodeling@gmail.com').toLowerCase().trim(),
  googleAiApiKey: process.env.GOOGLE_AI_API_KEY || '',
  groqApiKey: process.env.GROQ_API_KEY || '',
  aiPredictLeadMs: Number(process.env.AI_PREDICT_LEAD_MS || 90 * 60 * 1000),
  aiPredictWindowMs: Number(process.env.AI_PREDICT_WINDOW_MS || 5 * 60 * 1000),
  aiPredictJobIntervalMs: Number(process.env.AI_PREDICT_JOB_INTERVAL_MS || 5 * 60 * 1000),
  aiGeminiModel: process.env.AI_GEMINI_MODEL || 'gemini-2.5-flash',
  aiGroqModel: process.env.AI_GROQ_MODEL || 'llama-3.3-70b-versatile',
};
