import dotenv from 'dotenv';

dotenv.config();

export const env = {
  port: Number(process.env.PORT || 5000),
  mongodbUri: process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/mundial2026',
  jwtSecret: process.env.JWT_SECRET || 'dev-secret-change-me',
  clientOrigin: process.env.CLIENT_ORIGIN || 'http://localhost:5173',
  worldCupApiUrl: process.env.WORLD_CUP_API_URL || 'https://worldcup26.ir',
  worldCupSyncEmail: process.env.WORLD_CUP_SYNC_EMAIL || '',
  worldCupSyncPassword: process.env.WORLD_CUP_SYNC_PASSWORD || '',
  syncIntervalMs: Number(process.env.SYNC_INTERVAL_MS || 60000),
  syncIntervalLiveMs: Number(process.env.SYNC_INTERVAL_LIVE_MS || 15000),
  kickoffWatchIntervalMs: Number(process.env.KICKOFF_WATCH_MS || 15000),
  predictionLockReminderIntervalMs: Number(process.env.PREDICTION_LOCK_REMINDER_INTERVAL_MS || 60000),
  simulationEnabled: process.env.SIMULATION_ENABLED !== 'false',
  adminUsername: process.env.ADMIN_USERNAME || '',
  adminPassword: process.env.ADMIN_PASSWORD || '',
  adminJwtExpires: process.env.ADMIN_JWT_EXPIRES || '8h',
  footballDataApiToken: process.env.FOOTBALL_DATA_API_TOKEN || '',
  footballDataApiUrl: process.env.FOOTBALL_DATA_API_URL || 'https://api.football-data.org/v4',
  fifaApiUrl: process.env.FIFA_API_URL || 'https://api.fifa.com/api/v3',
  fifaCompetitionId: process.env.FIFA_COMPETITION_ID || '17',
  fifaSeasonId: process.env.FIFA_SEASON_ID || '285023',
  fifaReportAssetPrefix: process.env.FIFA_REPORT_ASSET_PREFIX || 'ce281',
  fifaReportIdBase: Number(process.env.FIFA_REPORT_ID_BASE || 12451),
  aiPredictionsEnabled: process.env.AI_PREDICTIONS_ENABLED !== 'false',
  aiUserEmail: (process.env.AI_USER_EMAIL || 'predictivemodeling@gmail.com').toLowerCase().trim(),
  cerebrasApiKey: process.env.CEREBRAS_API_KEY || '',
  googleAiApiKey: process.env.GOOGLE_AI_API_KEY || '',
  groqApiKey: process.env.GROQ_API_KEY || '',
  aiDefaultProvider: (process.env.AI_DEFAULT_PROVIDER || 'cerebras').toLowerCase().trim(),
  aiPredictLeadMs: Number(process.env.AI_PREDICT_LEAD_MS || 90 * 60 * 1000),
  aiPredictWindowMs: Number(process.env.AI_PREDICT_WINDOW_MS || 5 * 60 * 1000),
  aiPredictJobIntervalMs: Number(process.env.AI_PREDICT_JOB_INTERVAL_MS || 5 * 60 * 1000),
  aiCerebrasModel: process.env.AI_CEREBRAS_MODEL || 'gpt-oss-120b',
  aiGeminiModel: process.env.AI_GEMINI_MODEL || 'gemini-2.5-flash',
  aiGroqModel: process.env.AI_GROQ_MODEL || 'llama-3.3-70b-versatile',
  oddsApiKey: process.env.ODDS_API_KEY || '',
  oddsApiSport: process.env.ODDS_API_SPORT || 'soccer_fifa_world_cup',
  apiFootballKey: process.env.API_FOOTBALL_KEY || '',
  apiFootballUrl: process.env.API_FOOTBALL_URL || 'https://v3.football.api-sports.io',
  apiFootballSeason: process.env.API_FOOTBALL_SEASON || '2026',
  liveStreamEnabled: process.env.LIVE_STREAM_ENABLED !== 'false',
  la18hdBaseUrl: (process.env.LA18HD_BASE_URL || 'https://la18hd.com').replace(/\/$/, ''),
  la18hdScraperEnabled: process.env.LA18HD_SCRAPER_ENABLED === 'true',
  liveStreamUrls: {
    'fubo-youtube': process.env.LIVE_STREAM_URL_FUBO_YOUTUBE || '',
    'fubo-web': process.env.LIVE_STREAM_URL_FUBO_WEB || '',
    'fubo-app': process.env.LIVE_STREAM_URL_FUBO_APP || '',
    'fubo-roku': process.env.LIVE_STREAM_URL_FUBO_ROKU || '',
    'fubo-tubi': process.env.LIVE_STREAM_URL_FUBO_TUBI || '',
    'fubo-samsung': process.env.LIVE_STREAM_URL_FUBO_SAMSUNG || '',
    'fubo-sling': process.env.LIVE_STREAM_URL_FUBO_SLING || '',
    'fubo-prime': process.env.LIVE_STREAM_URL_FUBO_PRIME || '',
    'fubo-plex': process.env.LIVE_STREAM_URL_FUBO_PLEX || '',
    'fubo-lg': process.env.LIVE_STREAM_URL_FUBO_LG || '',
    'fubo-vizio': process.env.LIVE_STREAM_URL_FUBO_VIZIO || '',
    'fubo-tcl': process.env.LIVE_STREAM_URL_FUBO_TCL || '',
    'fubo-tablo': process.env.LIVE_STREAM_URL_FUBO_TABLO || '',
  },
  pushNotificationsEnabled: process.env.PUSH_NOTIFICATIONS_ENABLED === 'true',
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY || '',
  vapidPrivateKey: process.env.VAPID_PRIVATE_KEY || '',
  vapidSubject: process.env.VAPID_SUBJECT || 'mailto:admin@mundial2026.local',
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpUser: process.env.SMTP_USER || '',
  smtpPass: (process.env.SMTP_PASS || '').replace(/\s+/g, ''),
  smtpFrom: process.env.SMTP_FROM || process.env.SMTP_USER || '',
  appPublicName: process.env.APP_PUBLIC_NAME || 'Mundial 2026',
};
